server:
  port: 18115

spring:
  application:
    name: etc-svc-front-hunan
    active: DEV
##zuul api网关

api:
  token: 5988c914bd1749c79cf1a8526a7d531c
  url: 192.168.6.91:18110
secondissue:
  uploadPicture: 0  
  cancelType: 0
  logFlag: false
##支付宝签名相关
alipay1:
  private_key: 
  alipay_public_key:  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2H5Vhc+/T7qphnBYF7w1osL+bCsvwEaIb5py3mz70GOLyIK69UFLrNIGSA6x+opRM1lPLH3dyXg3SpaGEIPnOzDgDZC/HHoUA5HrY3UCo6hrmZWdXC7bNssHDIyiJ7ovRaVrGIEW+6DmLiwCTugJ78U/KDJA+EQDmbSyBMSGoXCLeHq54DYoyhTwLGfs9/alk0euLb2ALDgWcs8Gi+l5nLY0FsnyAN8XKV8Pb84MAiyclOst4NShIY6Hq+hzle/QoP0Rllq2h9vg42paaVMDw1TRCV+PEz0QrvUgUjBnrm8cXxUF1gDNBdb1f7JNkXs3g4JDpBdmHLAI+HrZd8ndEQIDAQAB
#  client:
#    app_id: 2021000114692216
#    server_url: http://openapi.dl.alipaydev.com/gateway.do
#    private_key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDOB+7d4u08HvfvzynZGZ1FMfKi/4kravQbBd+6O38Yn/b8AfOy+vHHm6CRFOwpAGT503SliRJgSBs6vCwrdAXZctYRzKkU7l4gCFMG8rL0kX1KWzYi3sQlsBylPay7cXVcjZiBNrxI752753L1C+JFP6yfbOSV2xn3xB4KlMRtLDcDYWHa2ffpS9nuFzY9YF5zt+63yxUhhQxe9ISeS1K+1YGrQCemjZG8908e5kuq/ywcL/lhHB4BJ8xEp0u9OuyUTCnJy84Y/ifTsxog8BXuDRPyzEChplssNUjH1RgHjpeCOPImypGuvbXq47KhEEPUW2qho5zIX0+UcdsZJ0XRAgMBAAECggEAXZLCzSnUf1q9VsArDHwSrquZvKf8X6jKxz8qtoVxGvkEDr7ANQi+KN8o1NvAynpwYfrE3q3bl7kIDOwLz4x5X6JFUX43SNdeDoRZWS1/U46EbfHxK3MreMZ8rBvPyK4mFGwG2KDIcQPLCt16m4rTMIpT13B4fQsuxxXeYwXgFIiQpSbVdWadnoZvZRwDeJF3p2kMOx9THnaMNnVakBuSKgpRd18tq4MnVRLreNk5rdtEvUtRtdINUgIAjCkFISw3XgeodRYCYG04EJtO7CEQNAzirZTUXaRjfFa1WXu33xrYyYAJdtYP/Q0fxY60xL8hcAAc2Zhaee6IsJPnuYPcBQKBgQDq549qQ/DzZV7FoIv51VIhGoJOwAI1XJtTvKBtzfjX4oKDmmjOzU4tVgCryxxU53IPwd8oXmvNKJkXVH4q8h4ILwBLBiaSEPtuIjcVSbo7Z99xY2Vt2z/17h1pFLYdJSdP+yDs7iDQKZe7BmdduOys9bRr+OCrVwDerEP/oEziewKBgQDgiJJtsT60z7cM5Jyc7VvF6VnsRZuQQesicJ7AbJ8k7zCjCeCv4/LLr6VUsWs2yW0KzXG5A2nJ70uBNBe+W08vOD7jNFPvyEQEh4+39IfBWVDzq13lcW1X//OU3zUoftXiqgxxtABVB6Mly6skex4KUN1uDt4I5P8oNnvCiPc9IwKBgQDQAgaz8b++uAgI9lac/3H/kErNUydhe0SsDL7/HMH64T/zK1sdrR1J9fsYJP5MjLorC+EBDUNmY0nVJ+OlQcqoMn6O8L5c357VcoTWW/gGPL/W105szhZAPv9aGpX9DvZV06nfRCpYSkxqt4v2qRcjPVvrtHG2J4/EnkSEar1KWwKBgQCxeuKbuD3DuGiN1WsCFBC1uMUuoLrdZW2SVIj3uyR0kmjUhutGvRze6iD6eB8yODdsEYax4sPNLcx1/ZJDEnPd9EypVWR/pcI1/l2Y374rFAmMAkn/IhB3PcbxRxoCv3cbaqTZf5m/nIDWUE4gUP0m1FKjOzdAupoB1EcxNwiPFwKBgQCBYKck0H/Yl3Z7RHAjpxsoV5gZnljxU0WDa7/QW0xr/c2SBcFY1tr7sV3wiz3bEo35Zou7xd++PCetCmd+5TaQ0nNwye1L75q6x9spzb64WHMtuXfZdCB9nWcKtVx1iFNpaqY6EM8poJ2/5kPTyu+qGm7XTEJNg4gpXEtGjhLWOw==
#    alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwIFLOUgY176uBA50E86KgJvoXwrUQ9KQiK2w4vS5jV6DJ6wX85dOy7i6bAY//KD5bk0fIvgWjSz4IOP306PekwaeI7nOVwFRMI0ZqY++vGQ7nrc2gNyGrHcN6T/aiyr9pWiVxmB9Mc84LiGeBzAd6rzBLCv+W40OAN3gppERV//Vl7Gj1m4iRIOgH9t6HkvJpSXmpr84Oi6fB7/jl3oIXqQFQ37wsXM3lh1TkqfqecEYgtreBp/ZOh0BD/w0B37NmTt8sVtfIIg7GM+AdAQJvLnuk61WegaX5fsTW0LpKOPy0KjpV5C3gqbkwMMyNXF52cDN6XZxfl8PJyeQ+k8Q2wIDAQAB
##rocketmq
#rocketmq:
#  group_id: GID_trawe_etc_dev_alipay_order_sync
#  access_key: LTAIkkhOA1BfHGrC
#  secret_key: 2TAASx8BX0Vy3OXsj0RJWEbpBxwx1Q
#  consume_thread_nums: 10
#  ONS_addr: http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet
#  send_msg_timeout_millis: 3000
#  topic: trawe_etc_dev
#  tag: alipay_order_sync
#  max_reconsume_times: 8
##限流
#flowlimit:
#  rules:
#    - pattern: /etc/.*
#      key: etc
#      tps: 30
##图片服务url
#image:
#  url: 192.168.6.91:18300
trawe:
   privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCxi/WQQoDhzqTb4D61Lx6TsLqmPO2N9Y9gXB2JQe7OFXBOa45akgdD0BUqabWaO0x8A5Xc1+drK3w/ZdMUV7nBX+xLLl6mZoQ9xkK5SpzTLHaT0VQbG0yMo4VonbzZLfjjMcoMcJB25+7OqNInv9ClYnzPPu4TvClPfwZaPSQT3Vvb4kmXfSsE5cMOW+RyN2aPvERdVczcFYuwqwaQy6nvWbtoI+O8MVtHbSRrgFeACevWUwaqIE+yRUvc3pWjCc6vz1a5z3I4BA29RMLCye9Vam8VfHgHLmG6LRmMmliSYXwC8iuMZWL7YFGeicLXkBLxPSOf0yEDYTiX1WXGxSJrAgMBAAECggEAeDucjxXKK6CB2fiQ3qfLIB71NzBZeuIJNysKQXIp4tt301NY8pKjYtPeEXvGpGx1ziGrcgOvzs6C9HfjKoqB26c24G7FYBBai27grpQNgaBBqLaAK18gRrlR1dfEFJriShDkj+oGms9T1BVVQ9/MzsLUXJB0L18j5pbR2XhAH0aMomP71GkqRs4Z4mKiJxTk1RECFOCI/ybhuw1TX6qIdEiaMvZoZRaSvHNjDvGVJfJNB4CChd//W+NqQ+/EkkcFZXVLicSSpasoZdCMah9oJGv5jZ/eYn3DbjZJozwEkcvCd8kNuV9uNmleU7Ez7rwh1bNo+GPsoUS7xsOrdr5gSQKBgQDumD15n2IsuHs8jjFRL7j/QtIKef6cTFiLyCxpH0dse/G9Yrl6eHCjUgWfZo9bsGLO5Pa7t15iC7t84V7EcJyOBaD+Ok/m6tg/2eW/Ws2NCCEmlURcy74crIZvD+wRfJtwjZtKFPqs5mnXHY6Jx1R27/+Bb+ZI1qUtDrv5WTcHfQKBgQC+f6WtJODlwrbzVTgElA5rZWhk09OE2UW9+M0Sc7zlGwfhES9k8nkJql7XW+NUZwOxf8H/hUd6mRaNdAg4sLxzzCJ4C01hlY1SVqlBQsgjuqVCAhUveIjq+JBiVzlOBnrpeAHO0LhBipjJX19fhr8iJWaA3YJeVMr3m/P9/iMGBwKBgEsnMv3zQTY66b56P3iGIqxsvMJGCPfsaFunMq3uB05ZgByaUzgLZddbx5+c630DAyyOHFWmfZk+ftDoIDSaEAYAKeTKM07WHEWIegCbNnG85MxFaiIcnwZjJXkoN8COUlvSjt532znI3f+/NJ2bZrSMBhwcRhodWivmHzl8a4P1AoGATeFPsWaXTzd4piib2ztQXdW6hSYYnoJZQd46sKWCf0O6x+fHsYRzuWDenzrgyHvJBcMOY9FwNI3rq27ZgZu3n7vAB8XPH+sNOLFXRufvfLPspfzF/n9PsohmNt4j/mMl0tcOHig0fA8WgZUtH5euAl659ksY5knSJMKsUJWaafcCgYEA4LT10dQHuwrA76hfAn/dGqasraVGCYULqw2+lJr60lenh86nWVillyeFGFZzeDn+V0ZL+/ub4igghT602ZJkum/78gZynFyC4aB0CPjzzATBU1zkJQu3ghcG8tKT/AMXiFpwmxTGLbFmm+Js1H13qlPpVN1ldvIn75bMIMGnx28=
   publickey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsYv1kEKA4c6k2+A+tS8ek7C6pjztjfWPYFwdiUHuzhVwTmuOWpIHQ9AVKmm1mjtMfAOV3Nfnayt8P2XTFFe5wV/sSy5epmaEPcZCuUqc0yx2k9FUGxtMjKOFaJ282S344zHKDHCQdufuzqjSJ7/QpWJ8zz7uE7wpT38GWj0kE91b2+JJl30rBOXDDlvkcjdmj7xEXVXM3BWLsKsGkMup71m7aCPjvDFbR20ka4BXgAnr1lMGqiBPskVL3N6VownOr89Wuc9yOAQNvUTCwsnvVWpvFXx4By5hui0ZjJpYkmF8AvIrjGVi+2BRnonC15AS8T0jn9MhA2E4l9VlxsUiawIDAQAB

aliyun:
  mqs:
    alipay:
      secretKey:  2TAASx8BX0Vy3OXsj0RJWEbpBxwx1Q
      accessKey:  LTAIkkhOA1BfHGrC
      name: alipay
      namesrvAddr: http://onsaddr.mq-internet-access.mq-internet.aliyuncs.com:80
      groups:
        hunan-netpub-ordersync:
          consumeThreadNums: 10
          #GID_trawe_etc_netpub_dev_order_sync
          #GID_trawe_etc_netpub_order_sync
          groupId: GID_trawe_etc_netpub_dev_order_sync
          name: hunan-netpub-ordersync
          topic: trawe_etc_netpub
          tag: netpub_order_sync
          autoStartProduce: true    #true表示启动生产者，false表示不启动，默认是true
          autoStartConsume: true    #true表示启动消费者，false表示不启动，默认是true


          
       
          
http:
  defaultMaxPerRoute: 50
  maxTotal: 100
  staleConnectionCheckEnabled: true
  socketTimeout: 10000
  connectTimeout: 1000
  connectionRequestTimeout: 500      
  
  
################
# 限流配置
################
flowlimit-test:
  # 扩展限流策略使用,目前为使用到
  env:
    key: value
  rules:
  # 正则表达式匹配url规则,匹配中了就跟进限流策略限流
  - pattern: /.*
    # 为空表示,使用默认匹配规则
    patternClass:
    # 为限流策略指定标识,如果key重复,多个正则匹配的规则,将会使用同一限流策略
    key: mix-1
    # 限制tps情况,真实值跟进压测情况填写,最好压测时调节此值看压测结果的变化
    tps: 150
    # 限流控制类,为空表示使用默认
    limiterClass:

  limitResponse:
    policyClass:
    value:
      code: 503
      msg: Service Resource Limited
      data:
        text: mix restful api flowlimit test  
        
#监控告警规则
etc-monitor:
  monitor-enable: true
  alert-url: https://oapi.dingtalk.com/robot/send?access_token=2b4bacf4795f3ac824c0659c2e3189b2d35172b7b973f0a9e636ba61b1e26fce
  alert-after-failures: 0
  alert-intervals-ms: 120000    
  
image:
  size: 150     
